# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: dot_usage
description: a file format and utility to control building, running and testing source code
github_username: beneills

# Build settings
markdown: kramdown
highlighter: rouge
